/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BankingApplication;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        BankingApplicationDriver classUnderTest = new BankingApplicationDriver();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
